version: '3'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'farmu-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'farmu'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'farmu'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'farmu'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:

networks:
  my-proxy-net:
    external:
      name: custom_network

